# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(0A0000)
$foreground = rgb(E4DFD5)
$color0 = rgb(0A0000)
$color1 = rgb(40242A)
$color2 = rgb(65564A)
$color3 = rgb(8B4F5C)
$color4 = rgb(8B4F5C)
$color5 = rgb(8B4F5C)
$color6 = rgb(867A65)
$color7 = rgb(D1C9BB)
$color8 = rgb(928C83)
$color9 = rgb(563038)
$color10 = rgb(867363)
$color11 = rgb(B9697B)
$color12 = rgb(B9697B)
$color13 = rgb(B9697B)
$color14 = rgb(B3A387)
$color15 = rgb(D1C9BB)
