# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E4DFD5
background         #0A0000
cursor             #B5A99C

active_tab_foreground     #0A0000
active_tab_background     #E4DFD5
inactive_tab_foreground   #E4DFD5
inactive_tab_background   #0A0000

active_border_color   #E4DFD5
inactive_border_color #0A0000
bell_border_color     #40242A

color0      #0A0000
color1		#40242A
color2		#65564A
color3		#8B4F5C
color4		#8B4F5C
color5		#8B4F5C
color6		#867A65
color7		#D1C9BB
color8		#928C83
color9		#563038
color10		#867363
color11		#B9697B
color12		#B9697B
color13		#B9697B
color14		#B3A387
color15		#D1C9BB
